#!bash
#
# Bash completion support for bitbake-dumpsig tool,
# compatible with Bitbake 1.39.0 and Yocto 2.5 (sumo) release.
#
# Copyright (C) 2018 Lukasz Gardon <lukasz.gardon@gmail.com>
#
# Distributed under the MIT License (MIT)
#

_bitbake_dumpsig()
{
    local cur prev opts_short opts_long tasks
    local bb_layers_conf bb_layers_md5 bb_recipes

    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts_short="-h -d -t"

    opts_long="--help --debug --task="

    tasks="build compile compile_ptest_base configure configure_ptest_base deploy \
           distrodata fetch image image_complete install install_ptest_base package \
           package_qa package_write_deb package_write_ipk package_write_rpm package_write_tar \
           packagedata patch populate_lic populate_sdk populate_sysroot prepare_recipe_sysroot \
           rm_work rm_work_all unpack checkpkg checkuri clean cleanall cleansstate devpyshell \
           devshell listtasks package_index bootimg bundle_initramfs rootfs testimage \
           testimage_auto compile_kernelmodules diffconfig kernel_checkout kernel_configcheck \
           kernel_configme kernel_menuconfig kernel_metadata menuconfig savedefconfig shared_workdir \
           sizecheck strip validate_branches spdx"

    if [[ "$prev" == "=" ]]; then
        prev="${COMP_WORDS[COMP_CWORD - 2]}"
    elif [[ "$cur" == "=" ]]; then
        cur=""
    fi

    case "$cur" in
        "--"*)
            COMPREPLY=( $(compgen -W "${opts_long}" -- ${cur}) )
            if [[ ${#COMPREPLY[@]} == 1 && ${COMPREPLY[0]} == "--"*"=" ]] ; then
                compopt -o nospace
            fi
            return 0
        ;;
        "-"*)
            COMPREPLY=( $(compgen -W "${opts_short}" -- ${cur}) )
            return 0
        ;;
    esac

    bb_layers_conf="conf/bblayers.conf"
    bb_layers_md5=".bb_layers_conf.md5"
    bb_recipes=".bb_recipes"

    _parse_recipes () {
        bitbake -s | sed '0,/^=.*/d' > $bb_recipes
    }

    if [ ! -e $bb_layers_conf ]; then
        return 0
    fi

    if [ "$prev" = "bitbake" -a "$cur" = "" ]; then
	    _parse_recipes
    fi

    md5sum --quiet --status -c $bb_layers_md5 2>/dev/null
    if [ $? != 0 -o ! -e $bb_recipes ]; then
         md5sum $bb_layers_conf > $bb_layers_md5
         _parse_recipes
    fi

    recipes=$(cat $bb_recipes)

    case "$prev" in
        "-t"|"--task")
	   COMPREPLY=( $(compgen -W "${recipes}" -- ${cur}) )
	   return 0
    esac

    if [[ ${COMP_WORDS[COMP_CWORD -2]} =~ "-t" ]] || [[ ${COMP_WORDS[COMP_CWORD -3]} == "--task" ]]; then 
        COMPREPLY=( $(compgen -W "${tasks}" -- ${cur}) )
	return 0
    fi
}
complete -F _bitbake_dumpsig bitbake-dumpsig
