#!bash
#
# Bash completion support for bitbake-whatchanged tool,
# compatible with Bitbake version 1.39.1.
#
# Copyright (C) 2018 Lukasz Gardon <lukasz.gardon@gmail.com>
#
# Distributed under the MIT License (MIT)
#

_bitbake_whatchanged()
{
    local cur prev opts_short opts_long recipes
    local bb_layers_conf bb_layers_md5 bb_recipes

    COMPREPLY=()

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    opts_short="-h -v"

    opts_long="--help --verbose"

    case "$cur" in
        "--"*)
            COMPREPLY=( $(compgen -W "${opts_long}" -- ${cur}) )
            return 0
        ;;
        "-"*)
            COMPREPLY=( $(compgen -W "${opts_short}" -- ${cur}) )
            return 0
        ;;
    esac

    bb_layers_conf="conf/bblayers.conf"
    bb_layers_md5=".bb_layers_conf.md5"
    bb_recipes=".bb_recipes"

    _parse_recipes () {
        bitbake -s | sed -e '0,/^=.*/d' -e '/^\s*$/d' -e '/^Summary:/d' | awk '{print $1}' > $bb_recipes
    }

    if [ ! -e $bb_layers_conf ]; then
        return 0
    fi

    if [ "$prev" = "bitbake" -a "$cur" = "" ]; then
	    _parse_recipes
    fi

    md5sum --quiet --status -c $bb_layers_md5 2>/dev/null
    if [ $? != 0 -o ! -e $bb_recipes ]; then
         md5sum $bb_layers_conf > $bb_layers_md5
         _parse_recipes
    fi

    recipes=$(cat $bb_recipes)

    COMPREPLY=( $(compgen -W "${recipes}" -- ${cur}) )
    return 0
}
complete -F _bitbake_whatchanged bitbake-whatchanged